---
- name: Create Gitlab Group Labels
  ansible.builtin.uri:
    url: "{{ gitlab_server_url }}/api/v4/groups/{{ group_path | replace( '/', '%2F') }}/labels"
    method: POST
    body_format: json
    status_code: 
      - 200
      - 201
      - 409
    return_content: true
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    body: >-
      {
        "name": "{{ item.name }}",
        "color": "{{ item.color }}",
        "description": "{{ item.description }}"
      }
  delegate_to: localhost
  failed_when: |
    gitlab_labels_group_create.status|int == 409
      and
    gitlab_labels_group_create.json.message != 'Label already exists'
  changed_when: >
    gitlab_labels_group_create.json.subscribed is defined
      and
    gitlab_labels_group_create.json.id is defined
  register: gitlab_labels_group_create
  with_items: "{{ group_labels }}"
  when: item.state | default('present') == 'present'
  no_log: true
  tags: 
    - gitlab
    - gitlab_labels
    - gitlab_labels_create
    - gitlab_labels_group
    - gitlab_labels_group_create


- name: Fetch Gitlab group Labels
  ansible.builtin.uri:
    url: "{{ gitlab_server_url }}/api/v4/groups/{{ group_path | replace( '/', '%2F') }}/labels"
    method: GET
    body_format: json
    status_code: 
      - 200
    return_content: true
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    body: >-
      {
        "only_group_labels": "true"
      }
  delegate_to: localhost
  changed_when: gitlab_labels_fetch.json | length | int > 0 
  register: gitlab_labels_fetch
  when: fetch | default('false') == 'true'
  no_log: true
  tags: 
    - always


- name: Delete Gitlab Group Labels
  ansible.builtin.uri:
    url: "{{ gitlab_server_url }}/api/v4/groups/{{ group_path | replace( '/', '%2F') }}/labels/{{ item.name | urlencode }}"
    method: DELETE
    body_format: json
    status_code: 
      - 200
      - 204
      - 404
    return_content: true
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
  delegate_to: localhost
  register: gitlab_labels_group_delete
  failed_when: > 
    gitlab_labels_group_delete.status|int == 404
      and
    gitlab_labels_group_delete.json.message != '404 Label Not Found'
  with_items: "{{ group_labels }}"
  when: item.state | default('present') == 'absent'
  no_log: true
  tags: 
    - gitlab
    - gitlab_labels
    - gitlab_labels_delete
    - gitlab_labels_group
    - gitlab_labels_group_delete


- name: Create Gitlab project Labels
  ansible.builtin.uri:
    url: "{{ gitlab_server_url }}/api/v4/projects/{{ project_path | replace( '/', '%2F') }}/labels"
    method: POST
    body_format: json
    status_code: 
      - 200
      - 201
      - 409
    return_content: true
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    body: >-
      {
        "name": "{{ item.name }}",
        "color": "{{ item.color }}",
        "description": "{{ item.description }}"
      }
  delegate_to: localhost
  failed_when: >
      gitlab_labels_project_create.status|int == 409
        and
      gitlab_labels_project_create.json.message != 'Label already exists'
  changed_when: >
    gitlab_labels_project_create.json.subscribed is defined
      and
    gitlab_labels_project_create.json.id is defined
  register: gitlab_labels_project_create
  with_items: "{{ project_labels }}"
  when: item.state | default('present') == 'present'
  no_log: true
  tags: 
    - gitlab
    - gitlab_labels
    - gitlab_labels_create
    - gitlab_labels_project
    - gitlab_labels_project_create


- name: Fetch Gitlab project Labels
  ansible.builtin.uri:
    url: "{{ gitlab_server_url }}/api/v4/projects/{{ project_path | replace( '/', '%2F') }}/labels"
    method: GET
    body_format: json
    status_code: 
      - 200
    return_content: true
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    body: >-
      {
        "only_group_labels": "true"
      }
  delegate_to: localhost
  changed_when: gitlab_labels_project_fetch.json | length | int > 0 
  register: gitlab_labels_project_fetch
  when: fetch | default('false') == 'true'
  no_log: true
  tags: 
    - always


- name: Delete Gitlab Project Labels
  ansible.builtin.uri:
    url: "{{ gitlab_server_url }}/api/v4/projects/{{ project_path | replace( '/', '%2F') }}/labels/{{ item.name | urlencode }}"
    method: DELETE
    body_format: json
    status_code: 
      - 200
      - 204
      - 404
    return_content: true
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
  delegate_to: localhost
  register: gitlab_labels_project_delete
  failed_when: > 
    gitlab_labels_project_delete.status|int == 404
      and
    gitlab_labels_project_delete.json.message != '404 Label Not Found'

  with_items: "{{ project_labels }}"
  when: item.state | default('present') == 'absent'
  no_log: true
  tags: 
    - gitlab
    - gitlab_labels
    - gitlab_labels_delete
    - gitlab_labels_project
    - gitlab_labels_project_delete
