---

- name: build URL
  ansible.builtin.set_fact:
    gitlab_members_url: |
      {{ gitlab_server_url }}/api/v4/projects/{{ project_path | replace( '/', '%2F') }}/members/all?state=active
  when: project_path is defined
  no_log: true # Don't log data manipulation


- block:


  - name: Fetch All Project Members
    ansible.builtin.uri:
      url: "{{ gitlab_members_url }}"
      method: GET
      body_format: json
      status_code: [200,201]
      return_content: true
      headers:
        PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    register: gitlab_members_fetch_all
    no_log: true # api_token and cookie visible
    when: project_path is defined
    tags: 
      - gitlab
      - gitlab_members
      - gitlab_members_fetch
      - gitlab_members_fetch_all



  - name: Fact gitlab_members_fetch_all clean
    ansible.builtin.set_fact:
      gitlab_members_fetch_all: "{{ gitlab_members_fetch_all.json | default('') | from_yaml }}"
    when: gitlab_members_fetch_all.json | default('') | length | int > 0
    no_log: true # not required

  - name: Display found Project Members
    ansible.builtin.debug:
      msg: "{{ gitlab_members_fetch_all }}"


  when: task_gitlab_members_fetch_all | default(false) | bool


- name: Clear task variables
  ansible.builtin.set_fact:
    task_gitlab_members_fetch_all: false
    gitlab_members_url: ''
