---
- block:
  - name: Find Existing Issue Notes
    ansible.builtin.uri:
      url: "{{ gitlab_server_url }}/api/v4/projects/{{ project_path | replace('/', '%2F') }}/issues/{{ issue_iid }}/notes?per_page=100"
      method: GET
      body_format: json
      status_code: [200,201]
      return_content: true
      headers:
        PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    register: gitlab_issues_notes_fetch
    no_log: true # api_token and cookie visible
    when: >
      project_path is defined
        and
      issue_iid is defined
    tags:
      - gitlab
      - gitlab_issues
      - gitlab_issues_notes
      - gitlab_issues_notes_fetch


  - name: Fact gitlab_issues_notes_fetch clean
    ansible.builtin.set_fact:
      gitlab_issue_notes_existing: "{{ gitlab_issue_notes_existing + [ gitlab_issues_notes_fetch.json ]  }}"
    when: gitlab_issues_notes_fetch.json| default('')|length|int > 0
    no_log: true # Don't log data manipulation


  - name: Display found Gitlab Issue Notes
    ansible.builtin.debug:
      msg: "{{ gitlab_issue_notes_existing }}"



  when: task_gitlab_issues_notes_fetch | default(false) | bool


- block:


  - name: Reply to gitlab discussion
    ansible.builtin.uri:
      url: "{{ gitlab_server_url }}/api/v4/projects/{{ project_path | replace('/', '%2F') }}/issues/{{ issue_iid }}/discussions/{{ note_id }}/notes?note_id={{ noteable_id }}&body={{ note_body }}"
      method: POST
      body_format: json
      status_code: [200,201]
      return_content: true
      headers:
        PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    register: gitlab_issues_discussion_reply
    no_log: true # api_token and cookie visible
    when: >
      project_path is defined
        and
      issue_iid is defined
    tags:
      - gitlab
      - gitlab_issues
      - gitlab_issues_notes
      - gitlab_issues_discussion_reply


  - name: Pause for 5 seconds for gitlab to catchup
    ansible.builtin.pause:
      seconds: 5


  - name: Display Reply to gitlab Discussion
    ansible.builtin.debug:
      msg: "{{ gitlab_issues_discussion_reply.json | from_yaml }}"
    when: gitlab_issues_discussion_reply.json | default('') | length | int > 0


  when: task_gitlab_issues_discussion_reply | default(false) | bool


- block:


  - name: Add a Comment to Gitlab Issue {{ issue_iid }}
    ansible.builtin.uri:
      url: "{{ gitlab_server_url }}/api/v4/projects/{{ project_path | replace('/', '%2F') }}/issues/{{ issue_iid }}/notes?body={{ note_body | urlencode }}"
      method: POST
      body_format: json
      status_code: [200,201]
      return_content: true
      headers:
        PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    register: gitlab_issues_note_create
    no_log: true # api_token and cookie visible
    when: >
      project_path is defined
    tags:
      - gitlab
      - gitlab_issues
      - gitlab_issues_notes
      - gitlab_issues_note_create


  - name: Pause for 5 seconds for gitlab to catchup
    ansible.builtin.pause:
      seconds: 5


  - name: Display created Gitlab note
    ansible.builtin.debug:
      msg: "{{ gitlab_issues_note_create.json | from_yaml }}"
    when: gitlab_issues_note_create.json | default('') | length | int > 0


  when: task_gitlab_issues_note_create | default(false) | bool


- block:


  - name: Edit a comment under Gitlab Issue {{ issue_iid }}
    ansible.builtin.uri:
      url: "{{ gitlab_server_url }}/api/v4/projects/{{ project_path | replace('/', '%2F') }}/issues/{{ issue_iid }}/notes/{{ note_id }}?body={{ note_body | urlencode }}"
      method: PUT
      body_format: json
      status_code: [200,201]
      return_content: true
      headers:
        PRIVATE-TOKEN: "{{ gitlab_api_token }}"
    register: gitlab_issues_note_edit
    no_log: true # api_token and cookie visible
    when: >
      project_path is defined
    tags:
      - gitlab
      - gitlab_issues
      - gitlab_issues_notes
      - gitlab_issues_note_create


  - name: Pause for 5 seconds for gitlab to catchup
    ansible.builtin.pause:
      seconds: 5


  - name: Display edited Gitlab note
    ansible.builtin.debug:
      msg: "{{ gitlab_issues_note_edit.json | from_yaml }}"
    when: gitlab_issues_note_edit.json | default('') | length | int > 0


  when: task_gitlab_issues_note_edit | default(false) | bool


- block:


  - name: Comment on Merge Request
    ansible.builtin.uri:
      url: "https://gitlab.com/api/v4/projects/{{ project_path | replace('/', '%2F') }}/merge_requests/{{ merge_request_iid }}/notes"
      method: POST
      body_format: json
      status_code: [200, 201, 202]
      return_content: true
      headers:
        PRIVATE-TOKEN: "{{ gitlab_api_token  }}"
      body:
        body: "{{ merge_request_comment }}"
    register: gitlab_merge_request_notes_create
    no_log: true # api_token and cookie visible


  - name: Pause for 5 seconds for gitlab to catchup
    ansible.builtin.pause:
      seconds: 5


  - name: Display Merge Request comment
    ansible.builtin.debug:
      msg: "{{ gitlab_merge_request_notes_create.json | from_yaml }}"
    when: gitlab_merge_request_notes_create.json | default('') | length | int > 0


  when: task_gitlab_merge_request_notes_create | default(false) | bool


- name: Clear task variables
  ansible.builtin.set_fact:
    task_gitlab_issues_note_create: false
    task_gitlab_issues_note_edit: false
    task_gitlab_issues_notes_fetch: false
    task_gitlab_issues_notes_reply: false
    task_gitlab_issues_discussion_reply: false
    task_gitlab_merge_request_notes_create: false
