---
- name: Find Existing Issue Notes
  ansible.builtin.uri:
    url: "{{ gitlab_server_url }}/api/v4/projects/{{ project_path }}/issues/{{ issue_iid }}/notes"
    method: GET
    body_format: json
    status_code: [200,201]
    return_content: true
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
  register: gitlab_issues_notes_fetch
  no_log: true
  when: >
    project_path is defined
      and
    issue_iid is defined
  tags:
    - gitlab
    - gitlab_issues
    - gitlab_issues_notes
    - gitlab_issues_notes_fetch


- name: Fact gitlab_issues_notes_fetch clean
  ansible.builtin.set_fact:
    gitlab_issue_notes_existing: "{{ gitlab_issue_notes_existing + [ gitlab_issues_notes_fetch.json ]  }}"
  when: gitlab_issues_notes_fetch.json| default('')|length|int > 0
  no_log: true # Don't log data manipulation
