---
- name: Fetch a single project
  ansible.builtin.uri:
    url: "{{ gitlab_server_url }}/api/v4/projects/{{ project_path | replace('/', '%2F') }}"
    method: GET
    body_format: json
    status_code: [200,201]
    return_content: true
    headers:
      PRIVATE-TOKEN: "{{ gitlab_api_token }}"
  register: gitlab_project_fetch
  no_log: true # api_token and cookie visible
  when: project_path is defined
  tags: 
    - gitlab
    - gitlab_project
    - gitlab_project_fetch


- name: Fact gitlab_project_fetch clean
  ansible.builtin.set_fact:
    gitlab_existing_project: "{{ gitlab_project_fetch.json | default('') | from_yaml }}"
    gitlab_project_url: "{{ gitlab_project_fetch.json.web_url }}"
  when: gitlab_project_fetch.json | default('') | length | int > 0
  no_log: true # Don't log data manipulation


- name: Display found Gitlab Project
  ansible.builtin.debug:
    msg: "{{ gitlab_existing_project }}"
  when: gitlab_project_fetch.json | default('') | length | int > 0
