include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/ansible-role.gitlab-ci.yaml


variables:
  MY_PROJECT_ID: "45705596"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/git_configuration.git"



# update to use the new gitlab-ci type 'ansible-role'




# .ansible_linter_defaults:
#   stage: validation
#   before_script:
#     - if [ "0$JOB_ROOT_DIR" == "0" ]; then ROOT_DIR=gitlab-ci; else ROOT_DIR=$JOB_ROOT_DIR ; fi
#     - echo "[DEBUG] ROOT_DIR[$ROOT_DIR]"
#     - mkdir -p "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME"
#     - mkdir -p "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/tests"
#     - export PYTHON_VERSION=`python -c 'import sys; version=sys.version_info[:3]; print("{0}.{1}.{2}".format(*version))'`
#     - apt update
#     - apt install --no-install-recommends -y git
#     - python3 -m venv env
#     - . env/bin/activate
#     - pip install --upgrade pip
#     - pip install -r $ROOT_DIR/ansible/requirements.txt
#     - mkdir $PYTHON_VERSION
#   script:
#     - ansible-lint -q --nocolor --parseable $ANSIBLE_LINT_PATH > "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/$PYTHON_VERSION-ansible-lint.log" 1>&1 || ANSIBLE_LINT=$?
#     - cat "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/$CI_JOB_NAME/$PYTHON_VERSION-ansible-lint.log" | ansible-lint-to-junit-xml > "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/tests/$PYTHON_VERSION-ansible-lint.junit.xml" 1>&1 || ANSIBLE_LINT_JUNIT=$?
#     - ls -la $PYTHON_VERSION
#     - if [ $ANSIBLE_LINT_JUNIT > 0 ]; then echo "Error ANSIBLE_LINT_JUNIT failed with $ANSIBLE_LINT_JUNIT"; fi
#     - if [ $ANSIBLE_LINT -ge 3 ]; then echo "ansible lint failed with $ANSIBLE_LINT"; exit $ANSIBLE_LINT; fi # don't fail the job?? 1=failed test, 2=failed command i.e. switch/flag
#   after_script:
#     - echo deactivate
#   artifacts:
#     expire_in: 3 days
#     when: always
#     paths:
#       - "artifacts/*"
#     reports:
#       junit:
#         - "$CI_PROJECT_DIR/artifacts/$CI_JOB_STAGE/tests/*.junit.xml"
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "master"'
#       when: never
#     - if: '$CI_COMMIT_TAG'
#       when: always
#     - if: '$CI_COMMIT_BRANCH'
#       when: always
#     - when: never






# Ansible Lint (python 3.6):
#   variables:
#     ANSIBLE_LINT_PATH: defaults/ handlers/ meta/ tasks/ templates/
#   extends:
#     - .ansible_linter_defaults
#   image: python:3.6-slim


# Ansible Lint (python 3.7):
#   variables:
#     ANSIBLE_LINT_PATH: defaults/ handlers/ meta/ tasks/ templates/
#   extends:
#     - .ansible_linter_defaults
#   image: python:3.7-slim


# Ansible Lint (python 3.8):
#   variables:
#     ANSIBLE_LINT_PATH: defaults/ handlers/ meta/ tasks/ templates/
#   extends:
#     - .ansible_linter_defaults
#   image: python:3.8-slim


# Ansible Lint (python 3.9):
#   variables:
#     ANSIBLE_LINT_PATH: defaults/ handlers/ meta/ tasks/ templates/
#   extends:
#     - .ansible_linter_defaults
#   image: python:3.9-slim




# Gitlab Release:
#   extends:
#     - .gitlab_release


# Github (Push --mirror):
#   extends:
#     - .git_push_mirror
