include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/ansible-role.gitlab-ci.yaml # ToDo: remove this line post merge of nofusscomputing/projects/gitlab-ci!33
      - template/automagic.gitlab-ci.yaml

variables:
  MY_PROJECT_ID: "45705596"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/git_configuration.git"
  PAGES_ENVIRONMENT_PATH: projects/git_configuration/


Submodule.Integration.Test:
  extends: .ansible_playbook
  stage: test
  variables:
    ansible_playbook: 'git_configuration.yaml'
    ansible_tags: 'submodule'
    PIPELINE_RUN_TRIGGER: 'false'
    PIPELINE_RUN_SCHEDULE: 'false'
    ANSIBLE_ROLES_PATH: $CI_PROJECT_DIR/roles
  before_script:
    - git clone -b $CI_COMMIT_BRANCH --depth=1 $CI_REPOSITORY_URL roles/git_configuration
    - rm -Rf /etc/ansible/roles/git_configuration
    - ls -la /etc/ansible/roles
  needs: []
  rules:
    - if: 
        $CI_COMMIT_TAG == null &&
        $CI_PIPELINE_SOURCE == "push" && 
        $CI_COMMIT_BRANCH != 'master' &&
        $CI_COMMIT_BRANCH != 'development' &&
        $CI_COMMIT_BRANCH != 'automated-tasks'
      exists:
        - ".nfc_automation.yaml"
      when: always
    - when: never 


Patch.from.Gitlab.Issues.Integration.Test:
  extends: .ansible_playbook
  stage: test
  variables:
    ansible_playbook: 'git_configuration.yaml'
    ansible_tags: 'gitlab_issue_patches'
    PIPELINE_RUN_TRIGGER: 'false'
    PIPELINE_RUN_SCHEDULE: 'false'
    ANSIBLE_ROLES_PATH: $CI_PROJECT_DIR/roles
  before_script:
    - git clone -b $CI_COMMIT_BRANCH --depth=1 $CI_REPOSITORY_URL roles/git_configuration
    - rm -Rf /etc/ansible/roles/git_configuration
    - ls -la /etc/ansible/roles
  needs: []
  rules:
    - if: 
        $CI_COMMIT_TAG == null &&
        $CI_PIPELINE_SOURCE == "push" && 
        $CI_COMMIT_BRANCH != 'master' &&
        $CI_COMMIT_BRANCH != 'development' &&
        $CI_COMMIT_BRANCH != 'automated-tasks'
      exists:
        - ".nfc_automation.yaml"
      when: always
    - when: never 


Ansible-roles.Submodule.Deploy:
  extends: .submodule_update_trigger
  variables:
    SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/ansible-roles
