include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/ansible-role.gitlab-ci.yaml
      - template/website.gitlab-ci.yaml


variables:
  MY_PROJECT_ID: "45705596"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/git_configuration.git"
  PAGES_ENVIRONMENT_PATH: projects/git_configuration/
