INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Git Configuration
repo_url: https://gitlab.com/nofusscomputing/projects/ansible/git_configuration
edit_uri: '/-/ide/project/nofusscomputing/projects/ansible/git_configuration/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Ansible:

    - projects/ansible/index.md
  
    - Roles:

      - projects/ansible/roles/index.md

      - Git Configuration:

        - projects/ansible/roles/git_configuration/index.md

        - Git:

          - projects/ansible/roles/git_configuration/git.md

          #- Automations:

          - Task files:

            - projects/ansible/roles/git_configuration/git/patch.md

            - projects/ansible/roles/git_configuration/git/repository.md
        
        - Gitlab:

          - projects/ansible/roles/git_configuration/gitlab.md

          - Automations:

            - projects/ansible/roles/git_configuration/patches_from_gitlab_issues.md

            - projects/ansible/roles/git_configuration/submodule.md

          - Task files:

            - projects/ansible/roles/git_configuration/gitlab/issues.md

            - projects/ansible/roles/git_configuration/gitlab/issues_patches.md

            - projects/ansible/roles/git_configuration/gitlab/members.md

            - projects/ansible/roles/git_configuration/gitlab/merge_request.md

            - projects/ansible/roles/git_configuration/gitlab/notes.md

            - projects/ansible/roles/git_configuration/gitlab/projects.md

            - projects/ansible/roles/git_configuration/gitlab/labels.md

        - Github:

          - projects/ansible/roles/git_configuration/github.md

          #- Automations:

          #- Task Files:

- Operations: 

  - operations/index.md

- Contact Us: contact.md

