INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Git Configuration
repo_url: https://gitlab.com/nofusscomputing/projects/ansible/git_configuration
edit_uri: '/-/ide/project/nofusscomputing/projects/ansible/git_configuration/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Ansible Roles:

    - Git Configuration:

      - projects/git_configuration/index.md

      - Gitlab:

        - projects/git_configuration/gitlab.md

        - Automations:

          - projects/git_configuration/submodule.md

        - Task files:

          - projects/git_configuration/gitlab/issues.md

          - projects/git_configuration/gitlab/issues_patches.md

          - projects/git_configuration/gitlab/notes.md

          - projects/git_configuration/gitlab/projects.md

          - projects/git_configuration/gitlab/labels.md

      - Github:

        - projects/git_configuration/github.md

        - Automations:

        - Task Files:

- Operations: 

  - operations/index.md

- Contact Us: contact.md

